#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <oasis_3_data_path>"
    exit 1
fi

python3 preprocessing/filter_scans.py --acq_params_csv=./data/oasis-3-acq-params.csv --src_scans_path=$1 --dst_scans_path=./data/oasis-3-raw-filtered
python3 preprocessing/run_unires.py --data=./data/oasis-3-raw-filtered
python3 preprocessing/crop_volumes.py --input=./data/oasis-3-raw-filtered --output=./data/oasis-3-unires